// Code generated by entc, DO NOT EDIT.

package ent

import (
	"compound/internal/data/ent/preference"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// Preference is the model entity for the Preference schema.
type Preference struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Key holds the value of the "key" field.
	// 关键值
	Key string `json:"key,omitempty"`
	// Value holds the value of the "value" field.
	// 值
	Value string `json:"value,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Preference) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case preference.FieldID:
			values[i] = new(sql.NullInt64)
		case preference.FieldKey, preference.FieldValue:
			values[i] = new(sql.NullString)
		case preference.FieldCreateTime, preference.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Preference", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Preference fields.
func (pr *Preference) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case preference.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pr.ID = int(value.Int64)
		case preference.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				pr.CreateTime = value.Time
			}
		case preference.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				pr.UpdateTime = value.Time
			}
		case preference.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				pr.Key = value.String
			}
		case preference.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				pr.Value = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Preference.
// Note that you need to call Preference.Unwrap() before calling this method if this Preference
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Preference) Update() *PreferenceUpdateOne {
	return (&PreferenceClient{config: pr.config}).UpdateOne(pr)
}

// Unwrap unwraps the Preference entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *Preference) Unwrap() *Preference {
	tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Preference is not a transactional entity")
	}
	pr.config.driver = tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Preference) String() string {
	var builder strings.Builder
	builder.WriteString("Preference(")
	builder.WriteString(fmt.Sprintf("id=%v", pr.ID))
	builder.WriteString(", create_time=")
	builder.WriteString(pr.CreateTime.Format(time.ANSIC))
	builder.WriteString(", update_time=")
	builder.WriteString(pr.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", key=")
	builder.WriteString(pr.Key)
	builder.WriteString(", value=")
	builder.WriteString(pr.Value)
	builder.WriteByte(')')
	return builder.String()
}

// Preferences is a parsable slice of Preference.
type Preferences []*Preference

func (pr Preferences) config(cfg config) {
	for _i := range pr {
		pr[_i].config = cfg
	}
}
