// Code generated by entc, DO NOT EDIT.

package accountctoken

import (
	"time"
)

const (
	// Label holds the string label denoting the accountctoken type in the database.
	Label = "account_ctoken"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldUser holds the string denoting the user field in the database.
	FieldUser = "user"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEnteredMarket holds the string denoting the entered_market field in the database.
	FieldEnteredMarket = "entered_market"
	// FieldCtokenBalance holds the string denoting the ctoken_balance field in the database.
	FieldCtokenBalance = "ctoken_balance"
	// FieldStoredBorrowBalance holds the string denoting the stored_borrow_balance field in the database.
	FieldStoredBorrowBalance = "stored_borrow_balance"
	// FieldBorrowIndex holds the string denoting the borrow_index field in the database.
	FieldBorrowIndex = "borrow_index"
	// FieldTotalUnderlyingSupplied holds the string denoting the total_underlying_supplied field in the database.
	FieldTotalUnderlyingSupplied = "total_underlying_supplied"
	// FieldTotalUnderlyingRedeemed holds the string denoting the total_underlying_redeemed field in the database.
	FieldTotalUnderlyingRedeemed = "total_underlying_redeemed"
	// FieldTotalUnderlyingBorrowed holds the string denoting the total_underlying_borrowed field in the database.
	FieldTotalUnderlyingBorrowed = "total_underlying_borrowed"
	// FieldTotalUnderlyingRepaid holds the string denoting the total_underlying_repaid field in the database.
	FieldTotalUnderlyingRepaid = "total_underlying_repaid"
	// FieldSupplyBalanceUnderlying holds the string denoting the supply_balance_underlying field in the database.
	FieldSupplyBalanceUnderlying = "supply_balance_underlying"
	// FieldBorrowBalanceUnderlying holds the string denoting the borrow_balance_underlying field in the database.
	FieldBorrowBalanceUnderlying = "borrow_balance_underlying"
	// FieldLifetimeSupplyInterestAccrued holds the string denoting the lifetime_supply_interest_accrued field in the database.
	FieldLifetimeSupplyInterestAccrued = "lifetime_supply_interest_accrued"
	// FieldLifetimeBorrowInterestAccrued holds the string denoting the lifetime_borrow_interest_accrued field in the database.
	FieldLifetimeBorrowInterestAccrued = "lifetime_borrow_interest_accrued"
	// FieldSafeWithdrawAmountUnderlying holds the string denoting the safe_withdraw_amount_underlying field in the database.
	FieldSafeWithdrawAmountUnderlying = "safe_withdraw_amount_underlying"
	// FieldCollateralValueInUsd holds the string denoting the collateral_value_in_usd field in the database.
	FieldCollateralValueInUsd = "collateral_value_in_usd"
	// FieldBorrowValueInUsd holds the string denoting the borrow_value_in_usd field in the database.
	FieldBorrowValueInUsd = "borrow_value_in_usd"
	// FieldUnderlyingPriceUsd holds the string denoting the underlying_price_usd field in the database.
	FieldUnderlyingPriceUsd = "underlying_price_usd"
	// FieldBlockNumber holds the string denoting the block_number field in the database.
	FieldBlockNumber = "block_number"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// Table holds the table name of the accountctoken in the database.
	Table = "account_ctokens"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "account_ctokens"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_tokens"
)

// Columns holds all SQL columns for accountctoken fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldUser,
	FieldAddress,
	FieldSymbol,
	FieldName,
	FieldEnteredMarket,
	FieldCtokenBalance,
	FieldStoredBorrowBalance,
	FieldBorrowIndex,
	FieldTotalUnderlyingSupplied,
	FieldTotalUnderlyingRedeemed,
	FieldTotalUnderlyingBorrowed,
	FieldTotalUnderlyingRepaid,
	FieldSupplyBalanceUnderlying,
	FieldBorrowBalanceUnderlying,
	FieldLifetimeSupplyInterestAccrued,
	FieldLifetimeBorrowInterestAccrued,
	FieldSafeWithdrawAmountUnderlying,
	FieldCollateralValueInUsd,
	FieldBorrowValueInUsd,
	FieldUnderlyingPriceUsd,
	FieldBlockNumber,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "account_ctokens"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"account_tokens",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultUser holds the default value on creation for the "user" field.
	DefaultUser string
	// DefaultAddress holds the default value on creation for the "address" field.
	DefaultAddress string
	// DefaultSymbol holds the default value on creation for the "symbol" field.
	DefaultSymbol string
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultEnteredMarket holds the default value on creation for the "entered_market" field.
	DefaultEnteredMarket bool
	// DefaultCtokenBalance holds the default value on creation for the "ctoken_balance" field.
	DefaultCtokenBalance string
	// DefaultStoredBorrowBalance holds the default value on creation for the "stored_borrow_balance" field.
	DefaultStoredBorrowBalance string
	// DefaultBorrowIndex holds the default value on creation for the "borrow_index" field.
	DefaultBorrowIndex string
	// DefaultTotalUnderlyingSupplied holds the default value on creation for the "total_underlying_supplied" field.
	DefaultTotalUnderlyingSupplied string
	// DefaultTotalUnderlyingRedeemed holds the default value on creation for the "total_underlying_redeemed" field.
	DefaultTotalUnderlyingRedeemed string
	// DefaultTotalUnderlyingBorrowed holds the default value on creation for the "total_underlying_borrowed" field.
	DefaultTotalUnderlyingBorrowed string
	// DefaultTotalUnderlyingRepaid holds the default value on creation for the "total_underlying_repaid" field.
	DefaultTotalUnderlyingRepaid string
	// DefaultSupplyBalanceUnderlying holds the default value on creation for the "supply_balance_underlying" field.
	DefaultSupplyBalanceUnderlying string
	// DefaultBorrowBalanceUnderlying holds the default value on creation for the "borrow_balance_underlying" field.
	DefaultBorrowBalanceUnderlying string
	// DefaultLifetimeSupplyInterestAccrued holds the default value on creation for the "lifetime_supply_interest_accrued" field.
	DefaultLifetimeSupplyInterestAccrued string
	// DefaultLifetimeBorrowInterestAccrued holds the default value on creation for the "lifetime_borrow_interest_accrued" field.
	DefaultLifetimeBorrowInterestAccrued string
	// DefaultSafeWithdrawAmountUnderlying holds the default value on creation for the "safe_withdraw_amount_underlying" field.
	DefaultSafeWithdrawAmountUnderlying string
	// DefaultCollateralValueInUsd holds the default value on creation for the "collateral_value_in_usd" field.
	DefaultCollateralValueInUsd string
	// DefaultBorrowValueInUsd holds the default value on creation for the "borrow_value_in_usd" field.
	DefaultBorrowValueInUsd string
	// DefaultUnderlyingPriceUsd holds the default value on creation for the "underlying_price_usd" field.
	DefaultUnderlyingPriceUsd string
	// DefaultBlockNumber holds the default value on creation for the "block_number" field.
	DefaultBlockNumber uint64
)
